#! /bin/bash
# Implementation details can be found in the pddl/generate_solutions section in the report

# Environment variables
export PLANUTILS_PREFIX="$HOME/.planutils"
export PATH="$PATH:$PLANUTILS_PREFIX/bin"

# Install 
planutils install -y downward

# iterate through all directories in the current folder
for dir in problems/*/; do
    dir_name="${dir%/}"
    base_name=$(basename "$dir_name")

    # check if the directory name is an integer
    if [[ "$base_name" =~ ^[0-9]+$ ]]
    then
        # create solutions directory
        mkdir -p "solutions/$base_name"

        # iterate through all files in the directory
        for file in "$dir_name"/*; do
            if [[ -f "$file" ]]
            then
                file_name=$(basename "$file")

                # check if the file name matches the pattern "problem{integer}.pddl"
                if [[ "$file_name" =~ ^problem([0-9]+)\.pddl$ ]]
                then
                    problem_number="${BASH_REMATCH[1]}"
                    solution_dir="solutions/$base_name"
                    mkdir -p "$solution_dir/"
                    solution_file="$solution_dir/solution${problem_number}"
                    downward --alias seq-opt-merge-and-shrink --plan-file "$solution_file" --search-time-limit 10000 domain.pddl "$file"
                    rm "$file"
                fi
            fi
        done
        rmdir "$dir_name"
    fi
done
rmdir problems

exit